#!/usr/bin/env bash

# Directories to be prepended to PATH
declare -a dirs_to_prepend=(
    # Ensure that this bins always takes precedence over `/usr/bin`
    "/usr/local/bin"
    "$HOME/bin"
)

# Directories to be appended to PATH
declare -a dirs_to_append=(
    "/usr/bin"
    "$HOME/.dotfiles/bin"
    "./node_modules/.bin" # Add local npm-installed package bin
    "/usr/local/share/npm/bin" # Add npm-installed package bin
)

# Prepend directories to PATH
for index in ${!dirs_to_prepend[*]}
do
    if [ -d ${dirs_to_prepend[$index]} ]; then
        # If these directories exist, then prepend them to existing PATH
        PATH="${dirs_to_prepend[$index]}:$PATH"
    fi
done

# Append directories to PATH
for index in ${!dirs_to_append[*]}
do
    if [ -d ${dirs_to_append[$index]} ]; then
        # If these bins exist, then append them to existing PATH
        PATH="$PATH:${dirs_to_append[$index]}"
    fi
done

unset dirs_to_prepend dirs_to_append

export PATH
