#!/usr/bin/env bash

DOTFILES_DIR=$HOME/.dotfiles

declare -a files=(
    $DOTFILES_DIR/bash/options # Options
    $DOTFILES_DIR/bash/exports # Exports
    $DOTFILES_DIR/bash/aliases # Aliases
    $DOTFILES_DIR/bash/functions/* # Functions
    $DOTFILES_DIR/bash/prompt # Custom bash prompt
    $DOTFILES_DIR/bash/completion # Autocompletion
    $HOME/.*.local # Local and private settings not under version control (e.g. git credentials)
    $DOTFILES_DIR/bash/paths # Path modifications (must source after `.bash_profile.local` in case of custom `brew` location)
)

# If these files are readable, source them
for index in ${!files[*]}
do
    if [[ -r ${files[$index]} ]]; then
        source ${files[$index]}
    fi
done

unset files
